version: '3'

services:
  client: 
  
  server:
    image: node:20-alpine
    volumes:
      - "./server:/var/www"  
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: sh -c "cd /var/www && npm install && npm start"
    networks:
      - backend
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.0
    volumes:
      - "./database/data:/data/db"
    ports: 
      - "27017:27017"
    env_file:
      - .env
    networks:
      - backend
  
networks:
  backend:
    driver: bridge
