version: '3'

services:
  server:
    image: node:20-alpine
    volumes:
      - "./server:/var/www"  
    ports:
      - "8081:3000"
    links:
      - db
    environment:
      - URL_MONGO=mongodb://api:docker1234@mongo
    command: sh -c "cd /var/www && npm install && npm start"

  db:
    image: mongo:4.0
    volumes:
      - "./database/data:/data/db"
    ports: 
      - "27017:27017"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_PASSWORD}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}